image: Visual Studio 2017

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

test_script:
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\FlexPath.Tests\bin\Debug\FlexPath.Tests.dll -noshadow" -filter:"+[FlexPath*]* -[FlexPath.Tests*]*" -output:".\FlexPath_coverage.xml"
- codecov -f "FlexPath_coverage.xml"
