image: Visual Studio 2017
configuration: Release

init:
- cmd: "set ProductBaseVersion=0.1.3"
- cmd: "echo ProductBaseVersion=%ProductBaseVersion%"
- cmd: "set ProductVersion=%ProductBaseVersion%.%APPVEYOR_BUILD_NUMBER%"
- cmd: "echo ProductVersion=%ProductVersion%"
- cmd: "set ProductLongVersion=%ProductVersion%-%APPVEYOR_REPO_BRANCH%"
- cmd: "echo ProductLongVersion=%ProductLongVersion%"
- cmd: appveyor UpdateBuild -Version "%ProductVersion%"

assembly_info:
  patch: true
  file: '**\FlexPath*\Properties\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '$(ProductLongVersion)'
  
before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

test_script:
- OpenCover.Console.exe -register:user -target:"nunit3-console.exe" -targetargs:".\FlexPath.Tests\bin\Debug\FlexPath.Tests.dll .\FlexPath.Tests\bin\Release\FlexPath.Tests.dll --result=myresults.xml;format=AppVeyor" -filter:"+[FlexPath*]* -[FlexPath.Tests*]*" -output:".\FlexPath_coverage.xml"

after_test:
- codecov -f "FlexPath_coverage.xml"

build:
  publish_nuget: true

artifacts:
  - path: 'FlexPath\bin\Release'
    name: FlexPath

deploy:
  tag: $(APPVEYOR_REPO_TAG_NAME)  # update the tag triggering this release deployment
  release: 'FlexPath $(ProductVersion)'
  description: 'Release for version $(ProductLongVersion)'
  draft: true
  provider: GitHub
  auth_token: $(GITHUB_RELEASE_TOKEN_ENCRYPTED) # your encrypted token from GitHub
  artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
  on:
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
